import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import useSWR from "swr";
import { Avatar, Card, CardHeader } from "@mui/material";
const inter = Inter({ subsets: ["latin"] });

const fetcher = (...args) => fetch(...args).then((res) => res.json());

function stringToColor(string) {
  let hash = 0;
  let i;

  /* eslint-disable no-bitwise */
  for (i = 0; i < string.length; i += 1) {
    hash = string.charCodeAt(i) + ((hash << 5) - hash);
  }

  let color = '#';

  for (i = 0; i < 3; i += 1) {
    const value = (hash >> (i * 8)) & 0xff;
    color += `00${value.toString(16)}`.slice(-2);
  }
  /* eslint-enable no-bitwise */

  return color;
}

function stringAvatar(name) {
  return {
    sx: {
      bgcolor: stringToColor(name),
    },
    children: `${name.split(' ')[0][0]}${name.split(' ')[1][0]}`,
  };
}

export default function Home() {
  console.log("api call");
  const mock = [
    {
      name: "Cohn Doe ",
      address: "1 Bach Mai , Hai Ba Trung",
      cityId: 1,
      city: {
        id: 1,
        name: "Ha Noi",
        code: "HANOI",
        zipcode: "100000",
        gpsCoordinates: "21.0278° N, 105.8342° E",
      },
    },
    {
      name: "Aane Doe",
      address: "2 Duy Tan, Cau Giay",
      cityId: 1,
      city: {
        id: 1,
        name: "Ha Noi",
        code: "HANOI",
        zipcode: "100000",
        gpsCoordinates: "21.0278° N, 105.8342° E",
      },
    },
    {
      name: "Jane Doo",
      address: "3 My Dinh, Nam Tu Liem",
      cityId: 1,
      city: {
        id: 1,
        name: "Ha Noi",
        code: "HANOI",
        zipcode: "100000",
        gpsCoordinates: "21.0278° N, 105.8342° E",
      },
    },
    {
      name: "Fohn Doo",
      address: "1 Phan Huy Thong, Tan Son Nhat",
      cityId: 2,
      city: {
        id: 2,
        name: "Ho Chi Minh",
        code: "HOCHIMINH",
        zipcode: "200000",
        gpsCoordinates: "10.8231° N, 106.6297° E",
      },
    },
    {
      name: "Baby Doe",
      address: "2 Nguyen Hue, Go Vap",
      cityId: 2,
      city: {
        id: 2,
        name: "Ho Chi Minh",
        code: "HOCHIMINH",
        zipcode: "200000",
        gpsCoordinates: "10.8231° N, 106.6297° E",
      },
    },
    {
      name: "Nanie Doe",
      address: "3 Nguyen Thi Thap, Binh Tan",
      cityId: 3,
      city: null,
    },
  ];

  const { data, error } = useSWR("http://localhost:8080/account", fetcher);
  //http://localhost:8080/account?detail=true
  if (error) {
    console.log("ERROR");
    console.log(error);
  }
  if (data) {
    console.log("got data");
    console.log(data);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {
          mock.map(user => {

            return <Card>
              <CardHeader
                avatar={<Avatar {...stringAvatar(user.name)}/>}
                title={user.name}
                subheader={user.address}
              />
            </Card>
          })
        }
      </main>
    </>
  );
}
